// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SDMS_Anon.proto

#include "SDMS_Anon.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace SDMS {
namespace Anon {
      template <typename>
PROTOBUF_CONSTEXPR VersionRequest::VersionRequest(::_pbi::ConstantInitialized) {}
struct VersionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionRequestDefaultTypeInternal() {}
  union {
    VersionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionRequestDefaultTypeInternal _VersionRequest_default_instance_;

inline constexpr VersionReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        release_year_{0u},
        release_month_{0u},
        release_day_{0u},
        release_hour_{0u},
        release_minute_{0u},
        api_major_{0u},
        api_minor_{0u},
        api_patch_{0u},
        component_major_{0u},
        component_minor_{0u},
        component_patch_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR VersionReply::VersionReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct VersionReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionReplyDefaultTypeInternal() {}
  union {
    VersionReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionReplyDefaultTypeInternal _VersionReply_default_instance_;

inline constexpr NackReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        err_code_{static_cast< ::SDMS::ErrorCode >(1)} {}

template <typename>
PROTOBUF_CONSTEXPR NackReply::NackReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct NackReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NackReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NackReplyDefaultTypeInternal() {}
  union {
    NackReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NackReplyDefaultTypeInternal _NackReply_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR GetAuthStatusRequest::GetAuthStatusRequest(::_pbi::ConstantInitialized) {}
struct GetAuthStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetAuthStatusRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetAuthStatusRequestDefaultTypeInternal() {}
  union {
    GetAuthStatusRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetAuthStatusRequestDefaultTypeInternal _GetAuthStatusRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR DailyMessageRequest::DailyMessageRequest(::_pbi::ConstantInitialized) {}
struct DailyMessageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DailyMessageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DailyMessageRequestDefaultTypeInternal() {}
  union {
    DailyMessageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DailyMessageRequestDefaultTypeInternal _DailyMessageRequest_default_instance_;

inline constexpr DailyMessageReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR DailyMessageReply::DailyMessageReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DailyMessageReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DailyMessageReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DailyMessageReplyDefaultTypeInternal() {}
  union {
    DailyMessageReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DailyMessageReplyDefaultTypeInternal _DailyMessageReply_default_instance_;

inline constexpr AuthenticateByTokenRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateByTokenRequest::AuthenticateByTokenRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthenticateByTokenRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateByTokenRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateByTokenRequestDefaultTypeInternal() {}
  union {
    AuthenticateByTokenRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateByTokenRequestDefaultTypeInternal _AuthenticateByTokenRequest_default_instance_;

inline constexpr AuthenticateByPasswordRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateByPasswordRequest::AuthenticateByPasswordRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthenticateByPasswordRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateByPasswordRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateByPasswordRequestDefaultTypeInternal() {}
  union {
    AuthenticateByPasswordRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateByPasswordRequestDefaultTypeInternal _AuthenticateByPasswordRequest_default_instance_;

inline constexpr AuthStatusReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        auth_{false} {}

template <typename>
PROTOBUF_CONSTEXPR AuthStatusReply::AuthStatusReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthStatusReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthStatusReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthStatusReplyDefaultTypeInternal() {}
  union {
    AuthStatusReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthStatusReplyDefaultTypeInternal _AuthStatusReply_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR AckReply::AckReply(::_pbi::ConstantInitialized) {}
struct AckReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AckReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AckReplyDefaultTypeInternal() {}
  union {
    AckReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AckReplyDefaultTypeInternal _AckReply_default_instance_;
}  // namespace Anon
}  // namespace SDMS
static ::_pb::Metadata file_level_metadata_SDMS_5fAnon_2eproto[10];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_SDMS_5fAnon_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_SDMS_5fAnon_2eproto = nullptr;
const ::uint32_t TableStruct_SDMS_5fAnon_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AckReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::NackReply, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::NackReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::NackReply, _impl_.err_code_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::NackReply, _impl_.err_msg_),
    1,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.release_year_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.release_month_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.release_day_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.release_hour_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.release_minute_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.api_major_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.api_minor_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.api_patch_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.component_major_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.component_minor_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::VersionReply, _impl_.component_patch_),
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::GetAuthStatusRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByPasswordRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByPasswordRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByPasswordRequest, _impl_.uid_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByPasswordRequest, _impl_.password_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByTokenRequest, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByTokenRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthenticateByTokenRequest, _impl_.token_),
    0,
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthStatusReply, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthStatusReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthStatusReply, _impl_.auth_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::AuthStatusReply, _impl_.uid_),
    1,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::DailyMessageRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::DailyMessageReply, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::DailyMessageReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::SDMS::Anon::DailyMessageReply, _impl_.message_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::SDMS::Anon::AckReply)},
        {8, 18, -1, sizeof(::SDMS::Anon::NackReply)},
        {20, -1, -1, sizeof(::SDMS::Anon::VersionRequest)},
        {28, 47, -1, sizeof(::SDMS::Anon::VersionReply)},
        {58, -1, -1, sizeof(::SDMS::Anon::GetAuthStatusRequest)},
        {66, 76, -1, sizeof(::SDMS::Anon::AuthenticateByPasswordRequest)},
        {78, 87, -1, sizeof(::SDMS::Anon::AuthenticateByTokenRequest)},
        {88, 98, -1, sizeof(::SDMS::Anon::AuthStatusReply)},
        {100, -1, -1, sizeof(::SDMS::Anon::DailyMessageRequest)},
        {108, 117, -1, sizeof(::SDMS::Anon::DailyMessageReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::SDMS::Anon::_AckReply_default_instance_._instance,
    &::SDMS::Anon::_NackReply_default_instance_._instance,
    &::SDMS::Anon::_VersionRequest_default_instance_._instance,
    &::SDMS::Anon::_VersionReply_default_instance_._instance,
    &::SDMS::Anon::_GetAuthStatusRequest_default_instance_._instance,
    &::SDMS::Anon::_AuthenticateByPasswordRequest_default_instance_._instance,
    &::SDMS::Anon::_AuthenticateByTokenRequest_default_instance_._instance,
    &::SDMS::Anon::_AuthStatusReply_default_instance_._instance,
    &::SDMS::Anon::_DailyMessageRequest_default_instance_._instance,
    &::SDMS::Anon::_DailyMessageReply_default_instance_._instance,
};
const char descriptor_table_protodef_SDMS_5fAnon_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017SDMS_Anon.proto\022\tSDMS.Anon\032\nSDMS.proto"
    "\"\n\n\010AckReply\"\?\n\tNackReply\022!\n\010err_code\030\001 "
    "\002(\0162\017.SDMS.ErrorCode\022\017\n\007err_msg\030\002 \001(\t\"\020\n"
    "\016VersionRequest\"\202\002\n\014VersionReply\022\024\n\014rele"
    "ase_year\030\001 \001(\r\022\025\n\rrelease_month\030\002 \001(\r\022\023\n"
    "\013release_day\030\003 \001(\r\022\024\n\014release_hour\030\004 \001(\r"
    "\022\026\n\016release_minute\030\005 \001(\r\022\021\n\tapi_major\030\006 "
    "\001(\r\022\021\n\tapi_minor\030\007 \001(\r\022\021\n\tapi_patch\030\010 \001("
    "\r\022\027\n\017component_major\030\t \001(\r\022\027\n\017component_"
    "minor\030\n \001(\r\022\027\n\017component_patch\030\013 \001(\r\"\026\n\024"
    "GetAuthStatusRequest\">\n\035AuthenticateByPa"
    "sswordRequest\022\013\n\003uid\030\001 \002(\t\022\020\n\010password\030\002"
    " \002(\t\"+\n\032AuthenticateByTokenRequest\022\r\n\005to"
    "ken\030\001 \002(\t\",\n\017AuthStatusReply\022\014\n\004auth\030\001 \002"
    "(\010\022\013\n\003uid\030\002 \001(\t\"\025\n\023DailyMessageRequest\"$"
    "\n\021DailyMessageReply\022\017\n\007message\030\001 \001(\t*\022\n\010"
    "Protocol\022\006\n\002ID\020\001"
};
static const ::_pbi::DescriptorTable* const descriptor_table_SDMS_5fAnon_2eproto_deps[1] =
    {
        &::descriptor_table_SDMS_2eproto,
};
static ::absl::once_flag descriptor_table_SDMS_5fAnon_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SDMS_5fAnon_2eproto = {
    false,
    false,
    656,
    descriptor_table_protodef_SDMS_5fAnon_2eproto,
    "SDMS_Anon.proto",
    &descriptor_table_SDMS_5fAnon_2eproto_once,
    descriptor_table_SDMS_5fAnon_2eproto_deps,
    1,
    10,
    schemas,
    file_default_instances,
    TableStruct_SDMS_5fAnon_2eproto::offsets,
    file_level_metadata_SDMS_5fAnon_2eproto,
    file_level_enum_descriptors_SDMS_5fAnon_2eproto,
    file_level_service_descriptors_SDMS_5fAnon_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SDMS_5fAnon_2eproto_getter() {
  return &descriptor_table_SDMS_5fAnon_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SDMS_5fAnon_2eproto(&descriptor_table_SDMS_5fAnon_2eproto);
namespace SDMS {
namespace Anon {
const ::google::protobuf::EnumDescriptor* Protocol_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_SDMS_5fAnon_2eproto);
  return file_level_enum_descriptors_SDMS_5fAnon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Protocol_internal_data_[] = {
    65537u, 0u, };
bool Protocol_IsValid(int value) {
  return 1 <= value && value <= 1;
}
// ===================================================================

class AckReply::_Internal {
 public:
};

AckReply::AckReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.AckReply)
}
AckReply::AckReply(
    ::google::protobuf::Arena* arena,
    const AckReply& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  AckReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.AckReply)
}









::google::protobuf::Metadata AckReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[0]);
}
// ===================================================================

class NackReply::_Internal {
 public:
  using HasBits = decltype(std::declval<NackReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(NackReply, _impl_._has_bits_);
  static void set_has_err_code(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_err_msg(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

NackReply::NackReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.NackReply)
}
inline PROTOBUF_NDEBUG_INLINE NackReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        err_msg_(arena, from.err_msg_) {}

NackReply::NackReply(
    ::google::protobuf::Arena* arena,
    const NackReply& from)
    : ::google::protobuf::Message(arena) {
  NackReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.err_code_ = from._impl_.err_code_;

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.NackReply)
}
inline PROTOBUF_NDEBUG_INLINE NackReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        err_msg_(arena),
        err_code_{static_cast< ::SDMS::ErrorCode >(1)} {}

inline void NackReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
NackReply::~NackReply() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.NackReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NackReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.err_msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void NackReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.NackReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.err_msg_.ClearNonDefaultToEmpty();
    }
    _impl_.err_code_ = 1;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NackReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 35, 2> NackReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NackReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_NackReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string err_msg = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(NackReply, _impl_.err_msg_)}},
    // required .SDMS.ErrorCode err_code = 1;
    {::_pbi::TcParser::FastEr1S1,
     {8, 1, 8, PROTOBUF_FIELD_OFFSET(NackReply, _impl_.err_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required .SDMS.ErrorCode err_code = 1;
    {PROTOBUF_FIELD_OFFSET(NackReply, _impl_.err_code_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional string err_msg = 2;
    {PROTOBUF_FIELD_OFFSET(NackReply, _impl_.err_msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }}, {{
    {1, 8},
  }}, {{
    "\23\0\7\0\0\0\0\0"
    "SDMS.Anon.NackReply"
    "err_msg"
  }},
};

::uint8_t* NackReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.NackReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required .SDMS.ErrorCode err_code = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_err_code(), target);
  }

  // optional string err_msg = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_err_msg();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.NackReply.err_msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.NackReply)
  return target;
}

::size_t NackReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.NackReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string err_msg = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_err_msg());
  }

  // required .SDMS.ErrorCode err_code = 1;
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_err_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData NackReply::_class_data_ = {
    NackReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* NackReply::GetClassData() const {
  return &_class_data_;
}

void NackReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<NackReply*>(&to_msg);
  auto& from = static_cast<const NackReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.NackReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_err_msg(from._internal_err_msg());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.err_code_ = from._impl_.err_code_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NackReply::CopyFrom(const NackReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.NackReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NackReply::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* NackReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void NackReply::InternalSwap(NackReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.err_msg_, &other->_impl_.err_msg_, arena);
  swap(_impl_.err_code_, other->_impl_.err_code_);
}

::google::protobuf::Metadata NackReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[1]);
}
// ===================================================================

class VersionRequest::_Internal {
 public:
};

VersionRequest::VersionRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.VersionRequest)
}
VersionRequest::VersionRequest(
    ::google::protobuf::Arena* arena,
    const VersionRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  VersionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.VersionRequest)
}









::google::protobuf::Metadata VersionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[2]);
}
// ===================================================================

class VersionReply::_Internal {
 public:
  using HasBits = decltype(std::declval<VersionReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(VersionReply, _impl_._has_bits_);
  static void set_has_release_year(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_release_month(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_release_day(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_release_hour(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_release_minute(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_api_major(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_api_minor(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_api_patch(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_component_major(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_component_minor(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_component_patch(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
};

VersionReply::VersionReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.VersionReply)
}
VersionReply::VersionReply(
    ::google::protobuf::Arena* arena, const VersionReply& from)
    : VersionReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE VersionReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void VersionReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, release_year_),
           0,
           offsetof(Impl_, component_patch_) -
               offsetof(Impl_, release_year_) +
               sizeof(Impl_::component_patch_));
}
VersionReply::~VersionReply() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.VersionReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void VersionReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void VersionReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.VersionReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.release_year_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.api_patch_) -
        reinterpret_cast<char*>(&_impl_.release_year_)) + sizeof(_impl_.api_patch_));
  }
  if (cached_has_bits & 0x00000700u) {
    ::memset(&_impl_.component_major_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.component_patch_) -
        reinterpret_cast<char*>(&_impl_.component_major_)) + sizeof(_impl_.component_patch_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* VersionReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 0, 0, 2> VersionReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VersionReply, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_VersionReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 release_year = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.release_year_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_year_)}},
    // optional uint32 release_month = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.release_month_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_month_)}},
    // optional uint32 release_day = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.release_day_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_day_)}},
    // optional uint32 release_hour = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.release_hour_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_hour_)}},
    // optional uint32 release_minute = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.release_minute_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_minute_)}},
    // optional uint32 api_major = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.api_major_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_major_)}},
    // optional uint32 api_minor = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.api_minor_), 6>(),
     {56, 6, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_minor_)}},
    // optional uint32 api_patch = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.api_patch_), 7>(),
     {64, 7, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_patch_)}},
    // optional uint32 component_major = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.component_major_), 8>(),
     {72, 8, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_major_)}},
    // optional uint32 component_minor = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.component_minor_), 9>(),
     {80, 9, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_minor_)}},
    // optional uint32 component_patch = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VersionReply, _impl_.component_patch_), 10>(),
     {88, 10, 0, PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_patch_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 release_year = 1;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_year_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 release_month = 2;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_month_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 release_day = 3;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_day_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 release_hour = 4;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_hour_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 release_minute = 5;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_minute_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 api_major = 6;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_major_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 api_minor = 7;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_minor_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 api_patch = 8;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.api_patch_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 component_major = 9;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_major_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 component_minor = 10;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_minor_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 component_patch = 11;
    {PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_patch_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* VersionReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.VersionReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 release_year = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_release_year(), target);
  }

  // optional uint32 release_month = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_release_month(), target);
  }

  // optional uint32 release_day = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_release_day(), target);
  }

  // optional uint32 release_hour = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_release_hour(), target);
  }

  // optional uint32 release_minute = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_release_minute(), target);
  }

  // optional uint32 api_major = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_api_major(), target);
  }

  // optional uint32 api_minor = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_api_minor(), target);
  }

  // optional uint32 api_patch = 8;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        8, this->_internal_api_patch(), target);
  }

  // optional uint32 component_major = 9;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        9, this->_internal_component_major(), target);
  }

  // optional uint32 component_minor = 10;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        10, this->_internal_component_minor(), target);
  }

  // optional uint32 component_patch = 11;
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        11, this->_internal_component_patch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.VersionReply)
  return target;
}

::size_t VersionReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.VersionReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional uint32 release_year = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_release_year());
    }

    // optional uint32 release_month = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_release_month());
    }

    // optional uint32 release_day = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_release_day());
    }

    // optional uint32 release_hour = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_release_hour());
    }

    // optional uint32 release_minute = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_release_minute());
    }

    // optional uint32 api_major = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_api_major());
    }

    // optional uint32 api_minor = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_api_minor());
    }

    // optional uint32 api_patch = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_api_patch());
    }

  }
  if (cached_has_bits & 0x00000700u) {
    // optional uint32 component_major = 9;
    if (cached_has_bits & 0x00000100u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_component_major());
    }

    // optional uint32 component_minor = 10;
    if (cached_has_bits & 0x00000200u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_component_minor());
    }

    // optional uint32 component_patch = 11;
    if (cached_has_bits & 0x00000400u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_component_patch());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData VersionReply::_class_data_ = {
    VersionReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* VersionReply::GetClassData() const {
  return &_class_data_;
}

void VersionReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<VersionReply*>(&to_msg);
  auto& from = static_cast<const VersionReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.VersionReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.release_year_ = from._impl_.release_year_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.release_month_ = from._impl_.release_month_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.release_day_ = from._impl_.release_day_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.release_hour_ = from._impl_.release_hour_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.release_minute_ = from._impl_.release_minute_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.api_major_ = from._impl_.api_major_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.api_minor_ = from._impl_.api_minor_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.api_patch_ = from._impl_.api_patch_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000700u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_impl_.component_major_ = from._impl_.component_major_;
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.component_minor_ = from._impl_.component_minor_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.component_patch_ = from._impl_.component_patch_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VersionReply::CopyFrom(const VersionReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.VersionReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool VersionReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* VersionReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void VersionReply::InternalSwap(VersionReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.component_patch_)
      + sizeof(VersionReply::_impl_.component_patch_)
      - PROTOBUF_FIELD_OFFSET(VersionReply, _impl_.release_year_)>(
          reinterpret_cast<char*>(&_impl_.release_year_),
          reinterpret_cast<char*>(&other->_impl_.release_year_));
}

::google::protobuf::Metadata VersionReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[3]);
}
// ===================================================================

class GetAuthStatusRequest::_Internal {
 public:
};

GetAuthStatusRequest::GetAuthStatusRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.GetAuthStatusRequest)
}
GetAuthStatusRequest::GetAuthStatusRequest(
    ::google::protobuf::Arena* arena,
    const GetAuthStatusRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  GetAuthStatusRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.GetAuthStatusRequest)
}









::google::protobuf::Metadata GetAuthStatusRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[4]);
}
// ===================================================================

class AuthenticateByPasswordRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthenticateByPasswordRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_._has_bits_);
  static void set_has_uid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_password(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

AuthenticateByPasswordRequest::AuthenticateByPasswordRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.AuthenticateByPasswordRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateByPasswordRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uid_(arena, from.uid_),
        password_(arena, from.password_) {}

AuthenticateByPasswordRequest::AuthenticateByPasswordRequest(
    ::google::protobuf::Arena* arena,
    const AuthenticateByPasswordRequest& from)
    : ::google::protobuf::Message(arena) {
  AuthenticateByPasswordRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.AuthenticateByPasswordRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateByPasswordRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        uid_(arena),
        password_(arena) {}

inline void AuthenticateByPasswordRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthenticateByPasswordRequest::~AuthenticateByPasswordRequest() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.AuthenticateByPasswordRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateByPasswordRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uid_.Destroy();
  _impl_.password_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthenticateByPasswordRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.AuthenticateByPasswordRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.uid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthenticateByPasswordRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 59, 2> AuthenticateByPasswordRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthenticateByPasswordRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // required string password = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_.password_)}},
    // required string uid = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_.uid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string uid = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_.uid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string password = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateByPasswordRequest, _impl_.password_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\47\3\10\0\0\0\0\0"
    "SDMS.Anon.AuthenticateByPasswordRequest"
    "uid"
    "password"
  }},
};

::uint8_t* AuthenticateByPasswordRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.AuthenticateByPasswordRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string uid = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_uid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.AuthenticateByPasswordRequest.uid");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required string password = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.AuthenticateByPasswordRequest.password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.AuthenticateByPasswordRequest)
  return target;
}

::size_t AuthenticateByPasswordRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.AuthenticateByPasswordRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // required string uid = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_uid());
    }

    // required string password = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_password());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthenticateByPasswordRequest::_class_data_ = {
    AuthenticateByPasswordRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthenticateByPasswordRequest::GetClassData() const {
  return &_class_data_;
}

void AuthenticateByPasswordRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthenticateByPasswordRequest*>(&to_msg);
  auto& from = static_cast<const AuthenticateByPasswordRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.AuthenticateByPasswordRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_uid(from._internal_uid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_password(from._internal_password());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateByPasswordRequest::CopyFrom(const AuthenticateByPasswordRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.AuthenticateByPasswordRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthenticateByPasswordRequest::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* AuthenticateByPasswordRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthenticateByPasswordRequest::InternalSwap(AuthenticateByPasswordRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata AuthenticateByPasswordRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[5]);
}
// ===================================================================

class AuthenticateByTokenRequest::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthenticateByTokenRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthenticateByTokenRequest, _impl_._has_bits_);
  static void set_has_token(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

AuthenticateByTokenRequest::AuthenticateByTokenRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.AuthenticateByTokenRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateByTokenRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        token_(arena, from.token_) {}

AuthenticateByTokenRequest::AuthenticateByTokenRequest(
    ::google::protobuf::Arena* arena,
    const AuthenticateByTokenRequest& from)
    : ::google::protobuf::Message(arena) {
  AuthenticateByTokenRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.AuthenticateByTokenRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateByTokenRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        token_(arena) {}

inline void AuthenticateByTokenRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthenticateByTokenRequest::~AuthenticateByTokenRequest() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.AuthenticateByTokenRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateByTokenRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthenticateByTokenRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.AuthenticateByTokenRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.token_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthenticateByTokenRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 50, 2> AuthenticateByTokenRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthenticateByTokenRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthenticateByTokenRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // required string token = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AuthenticateByTokenRequest, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string token = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateByTokenRequest, _impl_.token_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\5\0\0\0\0\0\0"
    "SDMS.Anon.AuthenticateByTokenRequest"
    "token"
  }},
};

::uint8_t* AuthenticateByTokenRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.AuthenticateByTokenRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string token = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.AuthenticateByTokenRequest.token");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.AuthenticateByTokenRequest)
  return target;
}

::size_t AuthenticateByTokenRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.AuthenticateByTokenRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // required string token = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthenticateByTokenRequest::_class_data_ = {
    AuthenticateByTokenRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthenticateByTokenRequest::GetClassData() const {
  return &_class_data_;
}

void AuthenticateByTokenRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthenticateByTokenRequest*>(&to_msg);
  auto& from = static_cast<const AuthenticateByTokenRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.AuthenticateByTokenRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateByTokenRequest::CopyFrom(const AuthenticateByTokenRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.AuthenticateByTokenRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthenticateByTokenRequest::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* AuthenticateByTokenRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthenticateByTokenRequest::InternalSwap(AuthenticateByTokenRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata AuthenticateByTokenRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[6]);
}
// ===================================================================

class AuthStatusReply::_Internal {
 public:
  using HasBits = decltype(std::declval<AuthStatusReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_._has_bits_);
  static void set_has_auth(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_uid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

AuthStatusReply::AuthStatusReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.AuthStatusReply)
}
inline PROTOBUF_NDEBUG_INLINE AuthStatusReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uid_(arena, from.uid_) {}

AuthStatusReply::AuthStatusReply(
    ::google::protobuf::Arena* arena,
    const AuthStatusReply& from)
    : ::google::protobuf::Message(arena) {
  AuthStatusReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.auth_ = from._impl_.auth_;

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.AuthStatusReply)
}
inline PROTOBUF_NDEBUG_INLINE AuthStatusReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        uid_(arena) {}

inline void AuthStatusReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.auth_ = {};
}
AuthStatusReply::~AuthStatusReply() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.AuthStatusReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthStatusReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.uid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void AuthStatusReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.AuthStatusReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.uid_.ClearNonDefaultToEmpty();
  }
  _impl_.auth_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AuthStatusReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 37, 2> AuthStatusReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthStatusReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string uid = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_.uid_)}},
    // required bool auth = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AuthStatusReply, _impl_.auth_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_.auth_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required bool auth = 1;
    {PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_.auth_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional string uid = 2;
    {PROTOBUF_FIELD_OFFSET(AuthStatusReply, _impl_.uid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\3\0\0\0\0\0"
    "SDMS.Anon.AuthStatusReply"
    "uid"
  }},
};

::uint8_t* AuthStatusReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.AuthStatusReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required bool auth = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_auth(), target);
  }

  // optional string uid = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_uid();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.AuthStatusReply.uid");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.AuthStatusReply)
  return target;
}

::size_t AuthStatusReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.AuthStatusReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string uid = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_uid());
  }

  // required bool auth = 1;
  if (cached_has_bits & 0x00000002u) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AuthStatusReply::_class_data_ = {
    AuthStatusReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* AuthStatusReply::GetClassData() const {
  return &_class_data_;
}

void AuthStatusReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AuthStatusReply*>(&to_msg);
  auto& from = static_cast<const AuthStatusReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.AuthStatusReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_uid(from._internal_uid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.auth_ = from._impl_.auth_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthStatusReply::CopyFrom(const AuthStatusReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.AuthStatusReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AuthStatusReply::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* AuthStatusReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void AuthStatusReply::InternalSwap(AuthStatusReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uid_, &other->_impl_.uid_, arena);
        swap(_impl_.auth_, other->_impl_.auth_);
}

::google::protobuf::Metadata AuthStatusReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[7]);
}
// ===================================================================

class DailyMessageRequest::_Internal {
 public:
};

DailyMessageRequest::DailyMessageRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.DailyMessageRequest)
}
DailyMessageRequest::DailyMessageRequest(
    ::google::protobuf::Arena* arena,
    const DailyMessageRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  DailyMessageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.DailyMessageRequest)
}









::google::protobuf::Metadata DailyMessageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[8]);
}
// ===================================================================

class DailyMessageReply::_Internal {
 public:
  using HasBits = decltype(std::declval<DailyMessageReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(DailyMessageReply, _impl_._has_bits_);
  static void set_has_message(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

DailyMessageReply::DailyMessageReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SDMS.Anon.DailyMessageReply)
}
inline PROTOBUF_NDEBUG_INLINE DailyMessageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

DailyMessageReply::DailyMessageReply(
    ::google::protobuf::Arena* arena,
    const DailyMessageReply& from)
    : ::google::protobuf::Message(arena) {
  DailyMessageReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:SDMS.Anon.DailyMessageReply)
}
inline PROTOBUF_NDEBUG_INLINE DailyMessageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        message_(arena) {}

inline void DailyMessageReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DailyMessageReply::~DailyMessageReply() {
  // @@protoc_insertion_point(destructor:SDMS.Anon.DailyMessageReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DailyMessageReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DailyMessageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:SDMS.Anon.DailyMessageReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DailyMessageReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2> DailyMessageReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DailyMessageReply, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DailyMessageReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // optional string message = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(DailyMessageReply, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string message = 1;
    {PROTOBUF_FIELD_OFFSET(DailyMessageReply, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\7\0\0\0\0\0\0"
    "SDMS.Anon.DailyMessageReply"
    "message"
  }},
};

::uint8_t* DailyMessageReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SDMS.Anon.DailyMessageReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string message = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "SDMS.Anon.DailyMessageReply.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SDMS.Anon.DailyMessageReply)
  return target;
}

::size_t DailyMessageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SDMS.Anon.DailyMessageReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string message = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DailyMessageReply::_class_data_ = {
    DailyMessageReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DailyMessageReply::GetClassData() const {
  return &_class_data_;
}

void DailyMessageReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DailyMessageReply*>(&to_msg);
  auto& from = static_cast<const DailyMessageReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SDMS.Anon.DailyMessageReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DailyMessageReply::CopyFrom(const DailyMessageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SDMS.Anon.DailyMessageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DailyMessageReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DailyMessageReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DailyMessageReply::InternalSwap(DailyMessageReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata DailyMessageReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SDMS_5fAnon_2eproto_getter, &descriptor_table_SDMS_5fAnon_2eproto_once,
      file_level_metadata_SDMS_5fAnon_2eproto[9]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Anon
}  // namespace SDMS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
